// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Synestra.Persistence;

#nullable disable

namespace Synestra.Persistence.Migrations
{
    [DbContext(typeof(SynestraDbContext))]
    [Migration("20260905180053_AddJobSubmissionIdempotency")]
    partial class AddJobSubmissionIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Synestra.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("JobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_definition_id");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("JobDefinitionId", "Type");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Synestra.Domain.Jobs.JobAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Number")
                        .IsUnique();

                    b.ToTable("job_attempts", (string)null);
                });

            modelBuilder.Entity("Synestra.Domain.Jobs.JobDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("job_definitions", (string)null);
                });

            modelBuilder.Entity("Synestra.Domain.Leases.Lease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("JobAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_attempt_id");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("JobAttemptId")
                        .IsUnique();

                    b.HasIndex("WorkerId");

                    b.ToTable("leases", (string)null);
                });

            modelBuilder.Entity("Synestra.Domain.Workers.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.HasKey("Id");

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("Synestra.Persistence.Jobs.JobSubmissionRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key")
                        .UseCollation("C");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_identity");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response");

                    b.HasKey("Key");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("job_submissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_job_submissions_key_format", "key <> '' AND key COLLATE \"C\" !~ '[^!-~]' AND position(',' in key) = 0");
                        });
                });

            modelBuilder.Entity("Synestra.Domain.Jobs.Job", b =>
                {
                    b.HasOne("Synestra.Domain.Jobs.JobDefinition", null)
                        .WithMany()
                        .HasForeignKey("JobDefinitionId", "Type")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Synestra.Domain.Jobs.JobAttempt", b =>
                {
                    b.HasOne("Synestra.Domain.Jobs.Job", null)
                        .WithMany("Attempts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synestra.Domain.Leases.Lease", b =>
                {
                    b.HasOne("Synestra.Domain.Jobs.JobAttempt", null)
                        .WithOne("Lease")
                        .HasForeignKey("Synestra.Domain.Leases.Lease", "JobAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synestra.Domain.Workers.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Synestra.Persistence.Jobs.JobSubmissionRecord", b =>
                {
                    b.HasOne("Synestra.Domain.Jobs.Job", null)
                        .WithOne()
                        .HasForeignKey("Synestra.Persistence.Jobs.JobSubmissionRecord", "JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Synestra.Domain.Jobs.Job", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Synestra.Domain.Jobs.JobAttempt", b =>
                {
                    b.Navigation("Lease");
                });
#pragma warning restore 612, 618
        }
    }
}
